.TH UNGUI 1 "13 Feb 2012"
.SH NAME
\fBUnGUI\fP \- Unix Standard GUI

.SH SYNOPSIS
.B ungui
.SH DESCRIPTION
.B UnGUI
is a graphical user interface which attempts to make visual a few
of the concepts behind a command-line interface, such as found on
a POSIX-compatible Operating System.  When combined with an X11
window manager, it can be the basis for a desktop environment.

.SH HELPING OUT
If you find a bug, please feel free to try fixing it yourself.
Your publicly announced changes may be incorporated upstream, with
due credit.

.SH AUTHORS
Eli Cohen
